CREATE TABLE `analysis_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`fileName` varchar(255) NOT NULL,
	`fileUrl` text,
	`fileKey` varchar(255),
	`status` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
	`totalKeywords` int DEFAULT 0,
	`increaseBidCount` int DEFAULT 0,
	`decreaseBidCount` int DEFAULT 0,
	`negativeCount` int DEFAULT 0,
	`reasonableCount` int DEFAULT 0,
	`pendingCount` int DEFAULT 0,
	`overallAcos` text,
	`overallConversionRate` text,
	`averageCpc` text,
	`analysisResult` json,
	`reportUrl` text,
	`reportKey` varchar(255),
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `analysis_reports_id` PRIMARY KEY(`id`)
);
